#root_path: '/app/Glioma' # data folder (parent)
root_path: '/app/Data/_Brain/Radiology/_Adult/_Glioma' # data folder (parent)
#root_path: 'Y:/Groups/IDIAGroup/Data/_Brain/Radiology/_Adult/_Glioma'

mri_sites:  # add as many dataset as nedeed (coded by site{n})
  site0: "UCSF-PDGM"
  site1: "LUMIERE"
  site2: "CCF"
  site3: "IVYGAP"
  site4: "xCures"
  site5: "TCGA-GBM"
  site6: "GBM_Cohort_brucegroup/UW-GBM"

mri_data: ["site6"] # data to be included in the pipeline

submodule_configs:
  preprocessing: "config/preprocessing_config.yaml"
  radiomics: "config/radiomics_config.yaml"
  
# Enabling modules
run_dicomSelection: True
run_dicomConversion: True
run_niftiSelection: True 
run_preprocessing: True
run_segmentation: False
run_radiomics: False
run_survival_train: False
run_survival_test: False
run_deep_learning: False
run_feature_visualization: False